name: Feature Branch CI

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build_t5-47-plus:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Cache dl
      id: cache-dl
      uses: actions/cache@v3
      with:
        path: dl/
        key: ${{ runner.os }}-${{ hashFiles('**/dl') }}
    - name: Install packages
      run: sudo apt-get install git make python3 python3-pip cmake quilt
    - name: Build T5-4.7 Plus
      run: |
        cp config_T5-4.7-Plus config
        make
    - name: Deliver firmware
      uses: actions/upload-artifact@v3
      with:
        name: LILYGO_T5-4.7-PLUS_firmware
        path: ./bin/esp32s3/LILYGO_T5-4.7-PLUS/